spring:
  main:
    lazy-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://resource-service:5002/authorization-service
          jwk-set-uri: http://resource-service:5002/authorization-service/oauth2/v1/jwks
  rsocket:
    server:
      transport: websocket
      port: 8080
      mapping-path: /message-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/message_service
jwt:
  issuer-uri: http://resource-service:5002/authorization-service

logging:
  level:
    talk:
      messageService: DEBUG
