spring:
  main:
    lazy-initialization: true
  rsocket:
    server:
      transport: websocket
      port: 8080
      mapping-path: /message-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/message_service
jwt:
  issuer-uri: http://resource-service:5002/authorization-service

logging:
  level:
    talk:
      messageService: DEBUG
